# Name of workflow
name: linter

# Trigger the workflow on push
on:
  - push

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install
        run: make install
      - name: Run linter
        run: make lint